{"id":"5448aaa1385b9d2ebf348bc5","idMemberCreator":"53cfc3dbf80a9a2e4631c72c","data":{"list":{"name":"In Progress (Max 9)","id":"53d0c20db03b0a44cfcca50b"},"board":{"shortLink":"0GuDZG62","name":"Cape Town - Kanban","id":"53d0c20db03b0a44cfcca509"},"card":{"shortLink":"hUPXosEB","idShort":290,"name":"CW - GCCW082 - Disable cases","id":"54488e95d0bbe061e0358924"},"text":"@gillianoberholzer \n\nOnly \"431296\" has been verified and the other Cancelled (not verified) as specified above.\nI can cancel the verified record as well.\n\nAbove it is mentioned that the capturer is \"unable\" to capture because the Judgment already exists. Is the same issue being experienced when capturing both judgment or just the verified one?"},"type":"commentCard","date":"2014-10-23T07:13:37.371Z","memberCreator":{"id":"53cfc3dbf80a9a2e4631c72c","avatarHash":null,"fullName":"Yasser Ogier","initials":"YO","username":"yasserogier"}}